<a href="https://colab.research.google.com/github/Aditi9289/AIMLMonth2023/blob/main/Major_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Credit Card Fraud Detection





In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
credit_card_data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0     0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1     0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2     1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3     1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4     2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62    0.0  
1  0.125895 -0.008983  0.014724    2.69    0.0  
2 -0.139097 -0.055353 -0.059752  378.66    0.0  
3 -0.221929  0.062723  0.061458  123.50    0.0  
4  0.502292  0.219422  0.215153   69.99    0.0  

[5 rows x 31 columns]

In [ ]:
credit_card_data.tail()

Time        V1        V2        V3        V4        V5        V6  \
3968  3617  1.134592  0.252051  0.488592  0.799826 -0.264819 -0.369918   
3969  3621 -1.338671  1.080974  1.291196  0.719258  0.101320  0.053896   
3970  3622 -0.339728 -2.417449  0.975517  2.537995 -1.720361  0.863005   
3971  3623 -0.368639  0.947432  1.707755  0.932092  0.292956  0.189100   
3972  3624 -0.663445  1.162921  1.508050  0.549405  0.231377 -0.106041   

            V7        V8        V9  ...       V21       V22       V23  \
3968 -0.243365  0.049761  1.210818  ... -0.351115 -0.851463  0.186169   
3969  0.001297 -0.917575  1.638510  ...  0.498030 -0.483932  0.037686   
3970  0.032965  0.026764  2.487139  ...  0.391639  0.264432 -0.735031   
3971  0.499330  0.132466  0.779412  ... -0.119045  0.056665 -0.172703   
3972  0.817977 -0.387026  1.488054  ... -0.420337 -0.361357       NaN   

           V24       V25       V26       V27       V28  Amount  Class  
3968  0.092463  0.020015  0.057976 -0.046611  0.012562   13.99    0.0  
3969  0.053566 -0.560078  0.230423 -0.119911  0.321847   27.43    0.0  
3970  0.450594  0.310022 -0.231357 -0.049872  0.153526  730.32    0.0  
3971  0.170073  0.139605 -0.420518  0.033794  0.005996    6.87    0.0  
3972       NaN       NaN       NaN       NaN       NaN     NaN    NaN  

[5 rows x 31 columns]

In [ ]:
credit_card_data.info

<bound method DataFrame.info of       Time        V1        V2        V3        V4        V5        V6  \
0        0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1        0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2        1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3        1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4        2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
...    ...       ...       ...       ...       ...       ...       ...   
3968  3617  1.134592  0.252051  0.488592  0.799826 -0.264819 -0.369918   
3969  3621 -1.338671  1.080974  1.291196  0.719258  0.101320  0.053896   
3970  3622 -0.339728 -2.417449  0.975517  2.537995 -1.720361  0.863005   
3971  3623 -0.368639  0.947432  1.707755  0.932092  0.292956  0.189100   
3972  3624 -0.663445  1.162921  1.508050  0.549405  0.231377 -0.106041   

            V7        V8        V9  ...       V21       V22       V23  \
0     

In [ ]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
credit_card_data['Class'].value_counts()

0.0    3970
1.0       2
Name: Class, dtype: int64

0>>Normal Transaction


1>>Fraud Transaction


In [ ]:
legit=credit_card_data[credit_card_data.Class == 0]
fraud=credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(3970, 31)
(2, 31)


In [ ]:
legit.Amount.describe()

count    3970.000000
mean       64.899597
std       213.612570
min         0.000000
25%         2.270000
50%        12.990000
75%        54.990000
max      7712.430000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      2.000000
mean     264.500000
std      374.059487
min        0.000000
25%      132.250000
50%      264.500000
75%      396.750000
max      529.000000
Name: Amount, dtype: float64

In [ ]:
credit_card_data.groupby('Class').mean()

Time        V1        V2        V3        V4        V5  \
Class                                                                  
0.0    1638.828463 -0.332459  0.308935  0.837446  0.011432 -0.029468   
1.0     439.000000 -2.677884 -0.602658 -0.260694  3.143275  0.418809   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0.0    0.053530  0.147357 -0.071642  0.056211  ...  0.059567  0.010282   
1.0   -1.245684 -1.105907  0.661932 -1.520521  ...  1.114625  0.589464   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0.0   -0.082957 -0.058743  0.029114  0.095244 -0.012637  0.044658  0.002668   
1.0    0.200214  0.455377  0.013198  0.162159  0.016239  0.004186 -0.053756   

           Amount  
Class              
0.0     64.899597  
1.0    264.500000  

[2 rows x 30 columns]

Number of fraud Transactions>>86

In [ ]:
legit_sample = legit.sample(n=86)

Concatenating two Dataframes

In [ ]:
new_dataset = pd.concat([legit_sample,fraud],axis=0)


In [ ]:
new_dataset.head()

Time        V1        V2        V3        V4        V5        V6  \
1484  1158  1.024159 -0.659599  1.162314  0.244697 -1.368166 -0.177201   
1865  1441 -0.568089  0.223634  2.784809  1.398554 -0.976417  1.181462   
820    626  1.162650 -0.059101  0.625173  0.946211 -0.825452 -0.913223   
2724  2269 -1.109727  0.281886  2.352982  0.275582  0.261140  0.174692   
1144   892 -0.654401  1.157197  0.978790  0.804280  1.181281  0.876832   

            V7        V8        V9  ...       V21       V22       V23  \
1484 -0.704552  0.205562  1.021309  ... -0.135463 -0.349356  0.041388   
1865 -0.350213  0.544987  0.184840  ...  0.434369  1.419537  0.025451   
820  -0.051476 -0.105709  0.591473  ... -0.207887 -0.520481  0.044754   
2724  0.824667 -0.378556 -0.475676  ...  0.138725  1.030442 -0.024171   
1144  1.019566 -0.280048  0.347691  ... -0.296787  0.102785 -0.352439   

           V24       V25       V26       V27       V28  Amount  Class  
1484  0.595586  0.032333  0.907650 -0.054028  0.016463   75.46    0.0  
1865  0.259867 -0.494201 -0.114422  0.237891  0.169842   82.74    0.0  
820   0.729893  0.367855  0.249399 -0.032991  0.018235   30.50    0.0  
2724  0.306227  0.220291  0.561473 -0.392341 -0.475499   52.75    0.0  
1144 -1.297371  0.191535 -0.183538  0.332333 -0.122636   13.27    0.0  

[5 rows x 31 columns]

In [ ]:
new_dataset.tail()

Time        V1        V2        V3        V4        V5        V6  \
2869  2429 -0.589242  0.811138  0.673065 -2.367305  0.539653 -0.554615   
3882  3439  1.233421  0.055006  0.138306  0.270547  0.073329  0.249750   
3283  2829 -0.955702  1.810282  1.149661  2.903563 -0.446984 -0.322646   
541    406 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545   
623    472 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823   

            V7        V8        V9  ...       V21       V22       V23  \
2869  0.751907 -1.001631  0.758659  ...  0.817240  0.221257 -0.290826   
3882 -0.209804  0.193696 -0.000651  ... -0.245253 -0.756414  0.064882   
3283  1.242339  0.072394 -2.226789  ...  0.126046  0.237544 -0.159115   
541  -2.537387  1.391657 -2.770089  ...  0.517232 -0.035049 -0.465211   
623   0.325574 -0.067794 -0.270953  ...  0.661696  0.435477  1.375966   

           V24       V25       V26       V27       V28  Amount  Class  
2869 -0.516941  0.159077 -0.798058  0.265488 -0.024997    1.00    0.0  
3882 -0.842824  0.189247  0.161774 -0.024253 -0.005396    0.89    0.0  
3283  0.743517  0.438712  0.323988 -0.157429 -0.018987  124.14    0.0  
541   0.320198  0.044519  0.177840  0.261145 -0.143276    0.00    1.0  
623  -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00    1.0  

[5 rows x 31 columns]

In [ ]:
new_dataset['Class'].value_counts()

0.0    86
1.0     2
Name: Class, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

Time        V1        V2        V3        V4        V5  \
Class                                                                  
0.0    1764.709302 -0.463578  0.213361  0.970963  0.074544 -0.082521   
1.0     439.000000 -2.677884 -0.602658 -0.260694  3.143275  0.418809   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0.0   -0.058843  0.171472 -0.249005 -0.043900  ...  0.144169 -0.063878   
1.0   -1.245684 -1.105907  0.661932 -1.520521  ...  1.114625  0.589464   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0.0    0.065597 -0.007956  0.056866  0.064370 -0.042879  0.027579 -0.006668   
1.0    0.200214  0.455377  0.013198  0.162159  0.016239  0.004186 -0.053756   

           Amount  
Class              
0.0     85.002093  
1.0    264.500000  

[2 rows x 30 columns]

In [ ]:
X = new_dataset.drop(columns='Class',axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

      Time        V1        V2        V3        V4        V5        V6  \
1484  1158  1.024159 -0.659599  1.162314  0.244697 -1.368166 -0.177201   
1865  1441 -0.568089  0.223634  2.784809  1.398554 -0.976417  1.181462   
820    626  1.162650 -0.059101  0.625173  0.946211 -0.825452 -0.913223   
2724  2269 -1.109727  0.281886  2.352982  0.275582  0.261140  0.174692   
1144   892 -0.654401  1.157197  0.978790  0.804280  1.181281  0.876832   
...    ...       ...       ...       ...       ...       ...       ...   
2869  2429 -0.589242  0.811138  0.673065 -2.367305  0.539653 -0.554615   
3882  3439  1.233421  0.055006  0.138306  0.270547  0.073329  0.249750   
3283  2829 -0.955702  1.810282  1.149661  2.903563 -0.446984 -0.322646   
541    406 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545   
623    472 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823   

            V7        V8        V9  ...       V20       V21       V22  \
1484 -0.704552  0.205562  1.021309  ..

In [ ]:
print(Y)

1484    0.0
1865    0.0
820     0.0
2724    0.0
1144    0.0
       ... 
2869    0.0
3882    0.0
3283    0.0
541     1.0
623     1.0
Name: Class, Length: 88, dtype: float64


In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(88, 30) (70, 30) (18, 30)


Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

Accuracy score

In [ ]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy of training  data: ',training_data_accuracy)

Accuracy of training  data:  1.0


In [ ]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy score on test data: ',test_data_accuracy)

Accuracy score on test data:  1.0


Customer Behaviour


In [ ]:
import numpy as np
import pandas as pd


In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/futurexskill/projects/main/knn-classification/purchase_history.csv")

In [ ]:
data.head()

Customer ID  Gender  Age  Salary Product ID  Price  Purchased
0            1  Female   49   61000        P01   2000          1
1            2    Male   36   30000        P02   2000          1
2            3  Female   26   81000        P02   3500          1
3            4  Female   32   74000        P01   7000          0
4            5  Female   42   56000        P01   5000          0

In [ ]:
data.count()

Customer ID    1000
Gender         1000
Age            1000
Salary         1000
Product ID     1000
Price          1000
Purchased      1000
dtype: int64

In [ ]:
len(data)

1000

In [ ]:
gender_encoded = pd.get_dummies(data['Gender'])

In [ ]:
gender_encoded

Female  Male
0         1     0
1         0     1
2         1     0
3         1     0
4         1     0
..      ...   ...
995       0     1
996       0     1
997       1     0
998       0     1
999       1     0

[1000 rows x 2 columns]

In [ ]:
gender_encoded = pd.get_dummies(data['Gender'],drop_first=True)

In [ ]:
gender_encoded

Male
0       0
1       1
2       0
3       0
4       0
..    ...
995     1
996     1
997     0
998     1
999     0

[1000 rows x 1 columns]

In [ ]:
data = pd.concat([data,gender_encoded],axis=1)


In [ ]:
data

Customer ID  Gender  Age  Salary Product ID  Price  Purchased  Male
0              1  Female   49   61000        P01   2000          1     0
1              2    Male   36   30000        P02   2000          1     1
2              3  Female   26   81000        P02   3500          1     0
3              4  Female   32   74000        P01   7000          0     0
4              5  Female   42   56000        P01   5000          0     0
..           ...     ...  ...     ...        ...    ...        ...   ...
995          996    Male   21   73000        P02   5000          1     1
996          997    Male   62   54000        P01   5000          0     1
997          998  Female   41   20000        P03   2000          0     0
998          999    Male   22   29000        P03   5000          0     1
999         1000  Female   49   36000        P03   3500          0     0

[1000 rows x 8 columns]

In [ ]:
x = data[['Male','Age','Salary','Price']].to_numpy()

In [ ]:
x

array([[    0,    49, 61000,  2000],
       [    1,    36, 30000,  2000],
       [    0,    26, 81000,  3500],
       ...,
       [    0,    41, 20000,  2000],
       [    1,    22, 29000,  5000],
       [    0,    49, 36000,  3500]])

In [ ]:
y = data['Purchased'].to_numpy()

In [ ]:
y

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
x_train

array([[    1,    26, 28000,  5000],
       [    1,    54, 21000,  7000],
       [    0,    42, 22000,  5000],
       ...,
       [    0,    59, 91000,  2000],
       [    0,    31, 82000,  2000],
       [    0,    20, 34000,  5000]])

In [ ]:
x_test

array([[     1,     54,  36000,   5000],
       [     0,     54,  60000,   7000],
       [     1,     25,  39000,   2000],
       [     0,     39,  38000,   7000],
       [     1,     28,  37000,   5000],
       [     1,     52,  42000,   2000],
       [     0,     43,  25000,   7000],
       [     0,     40,  22000,   5000],
       [     0,     18,  23000,   3500],
       [     1,     62,  40000,   5000],
       [     1,     53,  66000,   5000],
       [     0,     50,  38000,   7000],
       [     0,     49,  59000,   7000],
       [     0,     56,  97000,   2000],
       [     1,     41,  44000,   3500],
       [     1,     37,  74000,   2000],
       [     0,     51,  23000,   5000],
       [     1,     54,  29000,   2000],
       [     1,     30,  48000,   3500],
       [     1,     56,  87000,   3500],
       [     0,     61,  75000,   7000],
       [     1,     52,  49000,   7000],
       [     0,     38, 100000,   2000],
       [     0,     40,  79000,   5000],
       [     1, 

In [ ]:
y_train

array([0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,

In [ ]:
y_test

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0])

In [ ]:
len(x_train)

800

In [ ]:
len(x_test)

200

In [ ]:
len(y_train)

800

In [ ]:
len(y_test)

200

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [ ]:
x_train

array([[ 1.08347268, -1.09076887, -1.30749141,  0.30934614],
       [ 1.08347268,  0.97668947, -1.60377078,  1.39955279],
       [-0.92295821,  0.0906359 , -1.56144515,  0.30934614],
       ...,
       [-0.92295821,  1.34587846,  1.35902286, -1.32596384],
       [-0.92295821, -0.72157988,  0.97809225, -1.32596384],
       [-0.92295821, -1.53379565, -1.05353767,  0.30934614]])

In [ ]:
x_test

array([[ 0.91370804,  0.84165121, -0.92674628,  0.29135523],
       [-1.0944415 ,  0.84165121,  0.09493083,  1.3460348 ],
       [ 0.91370804, -1.16805526, -0.79903664, -1.29066412],
       [-1.0944415 , -0.19785214, -0.84160652,  1.3460348 ],
       [ 0.91370804, -0.96015459, -0.8841764 ,  0.29135523],
       [ 0.91370804,  0.70305076, -0.671327  , -1.29066412],
       [-1.0944415 ,  0.07934876, -1.39501496,  1.3460348 ],
       [-1.0944415 , -0.12855191, -1.5227246 ,  0.29135523],
       [-1.0944415 , -1.65315683, -1.48015472, -0.49965444],
       [ 0.91370804,  1.396053  , -0.75646676,  0.29135523],
       [ 0.91370804,  0.77235099,  0.35035011,  0.29135523],
       [-1.0944415 ,  0.56445032, -0.84160652,  1.3460348 ],
       [-1.0944415 ,  0.49515009,  0.05236095,  1.3460348 ],
       [-1.0944415 ,  0.98025166,  1.67001638, -1.29066412],
       [ 0.91370804, -0.05925169, -0.58618724, -0.49965444],
       [ 0.91370804, -0.33645258,  0.69090915, -1.29066412],
       [-1.0944415 ,  0.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
k= 5
knn = KNeighborsClassifier(n_neighbors=k)

In [ ]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred = knn.predict(x_test)

In [ ]:
y_pred

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0])

In [ ]:
y_test

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0])

In [ ]:
from sklearn.metrics import accuracy_score


In [ ]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.765

In [ ]:
import pickle

In [ ]:
with open('knn_model.pickle','wb') as f:
  pickle.dump(knn,f)


In [ ]:
with open('scaler.pickle','wb') as f:
  pickle.dump(scaler,f)

In [ ]:
import pickle
with open('/content/knn_model.pickle','rb') as f:
  knn_new = pickle.load(f)

In [ ]:
with open('/content/scaler.pickle','rb') as f:
  scaler_new = pickle.load(f)

In [ ]:
import pandas as pd
new_data = pd.read_csv("https://raw.githubusercontent.com/futurexskill/projects/main/knn-classification/new_customers.csv")

In [ ]:
new_data

Gender  Age  Salary  Product ID  Price
0    Male   24   38652           3   4446
1  Female   47   64727           1   5188
2    Male   46   54648           1   6193
3    Male   31   20018           3   4779
4    Male   58   77731           2   6855
5    Male   28   55478           1   6153
6  Female   48   54211           2   7588
7    Male   31   60076           3   5238
8  Female   42   29290           1   5418
9    Male   50   21445           1   5598

In [ ]:
len(new_data)

10

In [ ]:
gender_encoded_new = pd.get_dummies(data['Gender'],drop_first=True)

In [ ]:
gender_encoded

Male
0       0
1       1
2       0
3       0
4       0
..    ...
995     1
996     1
997     0
998     1
999     0

[1000 rows x 1 columns]

In [ ]:
data_new_2 = pd.concat([new_data,gender_encoded_new],axis=1)

In [ ]:
data_new_2

Gender   Age   Salary  Product ID   Price  Male
0      Male  24.0  38652.0         3.0  4446.0     0
1    Female  47.0  64727.0         1.0  5188.0     1
2      Male  46.0  54648.0         1.0  6193.0     0
3      Male  31.0  20018.0         3.0  4779.0     0
4      Male  58.0  77731.0         2.0  6855.0     0
..      ...   ...      ...         ...     ...   ...
995     NaN   NaN      NaN         NaN     NaN     1
996     NaN   NaN      NaN         NaN     NaN     1
997     NaN   NaN      NaN         NaN     NaN     0
998     NaN   NaN      NaN         NaN     NaN     1
999     NaN   NaN      NaN         NaN     NaN     0

[1000 rows x 6 columns]

In [ ]:
x_new = data_new_2[['Male','Age','Salary','Price']].to_numpy()

In [ ]:
x_new


array([[0.0000e+00, 2.4000e+01, 3.8652e+04, 4.4460e+03],
       [1.0000e+00, 4.7000e+01, 6.4727e+04, 5.1880e+03],
       [0.0000e+00, 4.6000e+01, 5.4648e+04, 6.1930e+03],
       ...,
       [0.0000e+00,        nan,        nan,        nan],
       [1.0000e+00,        nan,        nan,        nan],
       [0.0000e+00,        nan,        nan,        nan]])

In [ ]:
x_new_scale2 = scaler_new.fit_transform(x_new)


In [ ]:
x_new_scale2

array([[-0.95501094, -1.54774434, -0.48875298, -1.42543997],
       [ 1.04710843,  0.60971747,  0.93112246, -0.61159228],
       [-0.95501094,  0.51591478,  0.38228547,  0.49072164],
       ...,
       [-0.95501094,         nan,         nan,         nan],
       [ 1.04710843,         nan,         nan,         nan],
       [-0.95501094,         nan,         nan,         nan]])

In [ ]:
y_new_pred = knn.predict(x_test)


In [ ]:
y_new_pred

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0])

In [ ]:
data_new_2['will_Purchase'] = pd.Series(y_new_pred)


In [ ]:
data_new_2

Gender   Age   Salary  Product ID   Price  Male  will_Purchase
0      Male  24.0  38652.0         3.0  4446.0     0            1.0
1    Female  47.0  64727.0         1.0  5188.0     1            0.0
2      Male  46.0  54648.0         1.0  6193.0     0            0.0
3      Male  31.0  20018.0         3.0  4779.0     0            0.0
4      Male  58.0  77731.0         2.0  6855.0     0            0.0
..      ...   ...      ...         ...     ...   ...            ...
995     NaN   NaN      NaN         NaN     NaN     1            NaN
996     NaN   NaN      NaN         NaN     NaN     1            NaN
997     NaN   NaN      NaN         NaN     NaN     0            NaN
998     NaN   NaN      NaN         NaN     NaN     1            NaN
999     NaN   NaN      NaN         NaN     NaN     0            NaN

[1000 rows x 7 columns]

In [ ]:
data_new_2.to_csv("model_predictions.csv",index=False)