# **MINOR PROJECT**

---






In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv(robots.csv)

In [ ]:
import warningswarnings.filterwarnings(ignore)

# **TASK 1** - Exploratory Data Analysis

<-----------------------Question 1----------------------------->

In [ ]:
x = df[`source`].nunique()
x
5
y = df[`source`].value_counts()

In [ ]:
0    100000
1    100000
2    100000
3    100000
4    100000
name: source, dtype:np.np.int64

<-----------------------Question 2----------------------------->

In [ ]:
y
0    100000
1    100000
2    100000
3    100000
4    100000
name: source, dtype:int64

SyntaxError: ignored

In [ ]:
np,array(y)
array(100000, 100000, 100000, 100000, 100000)

In [ ]:
x = np.unique(df[`source`])

In [ ]:
x
array([0, 1, 2, 3, 4,])

<-----------------------Question 3----------------------------->

In [ ]:
data.isna().sum()
source    0
num1      0
num2      0
num3      1
num4      1
num5      1
num6      1
num7      1
num8      1
num9      1
num10     1
dtype: np.int64

SyntaxError: ignored

Summarizing your analysis and observation

In [ ]:
data = data.fillna(value`other`)

In [ ]:
data.isna().sum()
source    0
num1      0
num2      0
num3      0
num4      0
num5      0
num6      0
num7      0
num8      0
num9      0
num10     0
dtype: int64

<-----------------------Question 4----------------------------->

In [ ]:
class_distribution = data[`source`].value_counts()

# print the class distribution
print("class distribution:")
print(class_distribution)

# check if the dataset is balanced
is_balanced = all(class_distribution = class_distribution[0])

# print the result
if is_balanced:
    print("the dataset is balanced")


In [ ]:
class Distribution
0    65071
1    65071
2    65070
3    65070
4    65070
name: source, dtype: int64
the dataset is not balanced

In [ ]:
label_counts = data[`source`].value_counts()

# visualize the label counts using a pie chart
label_counts.plot(kind=`pie`, autopct='%1.1f%%')

# Add tittle
plt.tittle(`distributionof robot lables`)









<-----------------------Question 5----------------------------->

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(`ignore`)

In [ ]:
data = pd.read_csv(`robotics.csv`)

In [ ]:
data.dtypes
source     int64
num1       int64
num2       int64
num3       int64
num4     float64
num5     float64
num6     float64
num7     float64
num8     float64
num9     float64
num10    float64
dtype: object

In [ ]:
data = data.astype(`float64`)
source   float64
num1     float64
num2     float64
num3     float64
num4     float64
num5     float64
num6     float64
num7     float64
num8     float64
num9     float64
num10    float64
dtype: object


In [ ]:
# define the sequence spoken by robots
sequence = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
                    [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
                    [4, 8, 12, 16, 20, 24, 28, 32, 36, 40],
                    [5, 10, 15, 20, 25, 30, 35, 40, 45, 50,])

# compute the correlation matrix
correlation_matrix = np.corrcoef(sequence)


# **TASK 2** - Classification/Regression

Perform following steps on the same dataset which you used for EDA.
> - Data Preprocessing (as per requirement)
> - Feature Engineering
> - Split dataset in train-test (80:20 ratio)
> - Model selection
> - Model training
> - Model evaluation
> - Fine-tune the Model
> - Make predictions

Summarize your model's performance by evaluation metrices



In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
y = df[`source`]

In [ ]:
y
0        0
1        1
2        2
3        3
4        4

        ..
499995   0
499996   1
499997   2
499998   3
499999   4
name: source, length: 500000, dtype: int64


In [ ]:
x = df.drop(columns = `source`)

In [ ]:
X.head(5)
    num1      num2      num3      num4      num5      num6       num7       num8       num9       num10
0      2         5         2         5         6         2          1          8          1           3
1   1747      1749      1751      1758      1765      1767       1772       1774       1783        1785
2  65056    195168   1561344   7806720  31226880 187361280  749445120 6745006080  6745006080  6745006080
3   2855      2860      2865      2870      2875      2880       2885       2890        2895       2900
4  11440     57200    286000   1430000   7150000  35750000  178750000  893750000  4468750000  22343750000


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
x_train.shape , y_train.shape
((400000, 10), (400000, ))

In [ ]:
x_train

In [ ]:
array([[   9136,        9142,        9150,       9184,           9186,         9187 ]
       [   1860,        9300,       46500,  145312500,      726562500,   3632812500]
       [   8535,        8540,        8545,       8570,           8575,         8580]
       [    661,        5949,       41643,    1249290,        4997160,     19988640]
       [   7109,       28436,      113744,  2579713920,    7739141760,  38695708800]
       [   5271,        5276,        5281,        5306,          5311,         5316]])

In [ ]:
x_test = np.array(x_test)

In [ ]:
x_train.shape,y_train.shape
((400000, 10) , (400000,))

In [ ]:
y_test

In [ ]:
104241     1
199676     1
140199     4
132814     4
408697     2
          ..
66361      1
497228     3
152728     3
50155      0
240408     3
name:source, length: 100000, dtype:int64

In [ ]:
x_train.shape , y_train.shape
((100000, 10), (100000,))

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model = DecisionTreeClassifier(critirion=`entropy`)

In [ ]:
model.score(x_test , y_test)

In [ ]:
0.97381

In [ ]:
model.predict(x_test)
array([1, 1, 4, ....., 3, 0, 3])

In [ ]:
y_test

In [ ]:
104241     1
199676     1
140199     4
132814     4
408697     2
          ..
 66361     1
497228     3
152728     3
50155      0
240408     3
name: source, length: 100000, datatype: int64