In [1]:
print("Hello world")

Hello world


In [2]:
nums = [1, 2, 3, 4, 5]
nums

[1, 2, 3, 4, 5]

In [3]:
numsq = []

for i in nums:
    numsq.append(i**2)
    
print(numsq)

[1, 4, 9, 16, 25]


# Numpy

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr**2

array([ 1,  4,  9, 16, 25])

In [11]:
arr + 10

array([11, 12, 13, 14, 15])

In [12]:
arr*2

array([ 2,  4,  6,  8, 10])

In [13]:
len(arr)

5

In [15]:
arr.ndim

1

In [16]:
arr.shape

(5,)

In [17]:
np.arange(10, 15)

array([10, 11, 12, 13, 14])

In [22]:
m1 = np.arange(20, 39, 2)
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [23]:
m1[0]

20

In [24]:
m1[7]

34

In [25]:
m1[-2]

36

In [26]:
m1[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [27]:
# new in numpy. 
m1[ [2, 3, 6, -1] ]

array([24, 26, 32, 38])

## Slicing

In [28]:
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [31]:
m1[1:4]

array([22, 24, 26])

In [32]:
m1[-5:-1]

array([30, 32, 34, 36])

In [33]:
# reversing the order. 
m1[::-1]

array([38, 36, 34, 32, 30, 28, 26, 24, 22, 20])


# Masking
### Boolean Indexing

In [35]:
m1 + 10

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [36]:
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [41]:
mask = m1 < 30
mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [42]:
m1[mask]

array([20, 22, 24, 26, 28])

In [44]:
m1[m1>30]

array([32, 34, 36, 38])

In [53]:
m2 = np.random.randint(1, 20, 10)
m2

array([13, 10, 15, 14,  3, 13, 17,  2, 16, 10])

In [54]:
m2[m2%2==0]

array([10, 14,  2, 16, 10])

In [55]:
a = np.array([1,4,6])
b = np.array([3,5,8])

In [56]:
a

array([1, 4, 6])

In [57]:
b

array([3, 5, 8])

In [58]:
a+b

array([ 4,  9, 14])

In [59]:
np.max(a)

6

In [60]:
np.min(a)

1

In [61]:
np.average(a)

3.6666666666666665

In [62]:
[[1,2,3], [4,5,6], [7,8,9]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [65]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
mat.ndim

2

In [68]:
mat.shape

(3, 3)

In [69]:
len(mat)

3

In [71]:
# how many elements
mat.size

9

In [72]:
mat.sum()

45

In [73]:
np.sum(mat)

45

## NPS Case Study

In [82]:
scores = np.loadtxt('survey.txt', dtype = 'int')
scores

array([ 7, 10,  5, ...,  5,  9, 10])

In [83]:
scores.size

1167

In [84]:
scores.min()

1

In [85]:
scores.max()

10

In [87]:
promoters =  scores[scores >= 9]
len(promoters)

609

In [89]:
detractors = scores[scores<=6]
len(detractors)

332

In [92]:
NPS = 100*(len(promoters) - len(detractors))/ scores.size
NPS

23.736075407026565

In [95]:
round(NPS, 1)

23.7

#### Conclusion : Not very good NPS, hence company should _______

In [97]:
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [98]:
m1.cumsum()

array([ 20,  42,  66,  92, 120, 150, 182, 216, 252, 290])

# Pandas

In [100]:
import pandas as pd

In [ ]:
# .csv -> comma seprated values.
# .xlsx -> excel

In [102]:
titanic = pd.read_csv('titanic.csv')

In [103]:
type(titanic)

pandas.core.frame.DataFrame

In [104]:
titanic.shape

(891, 12)

In [109]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [110]:
titanic.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [112]:
titanic.tail(3)

PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [114]:
titanic['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [115]:
titanic['Survived'].unique()

array([0, 1])

In [117]:
titanic['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [124]:
titanic['Survived'].value_counts(normalize=True)

0    0.616162
1    0.383838
Name: Survived, dtype: float64

In [120]:
549/(891)

0.6161616161616161

In [121]:
342/(891)

0.3838383838383838

In [125]:
titanic['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [127]:
titanic['Age'].mean()

29.69911764705882

In [128]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [129]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [131]:
titanic.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [134]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [136]:
titanic[titanic['Survived'] == 0]

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
6              7         0       1                   McCarthy, Mr. Timothy J   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch           Ticket     Fare Cabin Embarked  
0      male  22.0      1      0        A/5 21171   7.2500   NaN        S  
4      male  35.0      0      0           373450   8.0500   NaN        S  
5      male   NaN      0      0           330877   8.4583   NaN        Q  
6      male  54.0      0      0            17463  51.8625   E46        S  
7      male   2.0      3      1           349909  21.0750   NaN        S  
..      ...   ...    ...    ...              ...      ...   ...      ...  
884    male  25.0      0      0  SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5           382652  29.1250   NaN        Q  
886    male  27.0      0      0           211536  13.0000   NaN        S  
888  female   NaN      1      2       W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0           370376   7.7500   NaN        Q  

[549 rows x 12 columns]

In [138]:
titanic[titanic['Survived'] == 0]['Age'].mean()

30.62617924528302